### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by hedrickj19** [skiadas/BattleFTP#11]
We currently assume we will use different types of inventory such as:
- Weapons
- Armour
- etc.

What other inventory types should we have?
Also, what style of weapons are we using? Swords? Guns? Shields? etc? What

**Comment by hedrickj19** [comment]
We will also set the attributes of each item. How will it effect the uses health, attack strength, etc.

**Comment by millerlu19** [comment]
I like the idea of using swords and shields to keep it old fashioned.  Also, that would be easier for us in combat to implement because with guns we would need a range of how far a gun can shoot, and with swords its all a very close range.  I vote swords and shields, and possibly other close quarter combat weapons.

**Comment by kenjarna** [comment]
Guns and swords. We need to have stats for each weapon (such as range, damage, multipliers, special effects, etc).

**Comment by Hayesb20** [comment]
Do we want to make it so the the AI use inventory to drop items when defeated?

**Comment by hedrickj19** [comment]
I do agree with @millerlu19  that sticking with close range weaponry could make combat and weapon implementation easier. We can make many forms of close range weaponry though.

**Comment by hedrickj19** [comment]
@Hayesb20 I like that idea. We could have the AI unit drop a random item when defeated and then the game could ask the user if they wish to pick up the item. The actually dropping of the item and prompting of the user may be the job of UI, AI, or environment. I think our group would just be in charge of implementing a random item method.

**Comment by millerlu19** [comment]
I am not 100% sure how it is supposed to be, but I think that inventory will not only have the list of the weapons but also the values of each weapon.  Then, us in combat would take the weapon variable and the value variable and make a list of tuples to match together the weapons and their respected damage value.

**Comment by hedrickj19** [comment]
Yeah we were thinking we would implement the weapons and how they affect the user attributes, so then you guys know how to use each weapon in combat.

**Comment by haques94** [comment]
@hedrickj19 Jetpacks. We need some god damn jetpacks.

**Comment by millerlu19** [comment]
@hedrickj19 since it is text based, we will not exactly need to know how each weapon is used, but we will know if the weapon hit the enemy, missed, or was blocked by a shield.  If hit, that is where the damage would come to play which we will have that information from you guys depending on how powerful the weapon is.
