### ISSUE TITLE
Brainstorm: Combat

### ISSUE THREAD

**Issue by kenjarna** [skiadas/BattleFTP#13]
Teams to coordinate with:
- Inventory
- Unit

Information we will need:
- Multipliers (if a weapon has extra damage...so a laser gun may have 5x multiplier applied to it)
- Hit probability

How should we calculate the amount of damage an action does? Are we going to take into account environment affects for damage purposes? If you go outside the area of play, do you automatically "die"? H

**Comment by millerlu19** [comment]
I like the idea if a limb (arm or leg) gets attacked to a certain point, that limb is gone, and there is a chance to find a health regeneration somewhere on campus to regain that limb before death

**Comment by millerlu19** [comment]
A successful attack to the head, neck, or chest results in death.
Also, if both arms and both legs are gone from the character, death.

**Comment by millerlu19** [comment]
Environment team would be in charge of if user falls off map.  They would notify us in combat, and the result of the fallen user will be death.

**Comment by amartens181** [comment]
Should this be keyboard smashing combat?

**Comment by millerlu19** [comment]
If keyboard smashing means the attack is made when the specific button on the keyboard is pressed, then I think that is the best way to do it. @amartens181

**Comment by veasy62** [comment]
Should we make random weather to affect damage in combat

**Comment by ghost** [comment]
Some other ideas for the boundaries:
* Slowly take damage when you exit the allowed area?
* Block the character from going further?

**Comment by millerlu19** [comment]
@veasy62 I like the idea of weather affecting combat, but I think weather could be used to affect accuracy of the attack instead of the weather damaging the users.

**Comment by millerlu19** [comment]
@haflg19 I like the idea of slowly taking damage when exiting the allowed area.  I think instead of blocking the character from going further, they can have a 10 second time limit to return to the allowed area.  If they do not get back to the correct area in time, then health of user goes all the way down resulting in death.

**Comment by walkert20** [comment]
Whenever you guys decide upon the possible actions of the units, could you send the ones the AI are to perform.  Also, just an idea I had, could you create some AI only actions that are "OP as f#ck".  We were planning on using them for high difficulty AI units.

**Comment by kenjarna** [comment]
@walkert20  did you want us to create the "move" set that all units can do? How would you like the user to be able to select those options and should certain actions only be allowed every so often or cost some sort of health/energy?

**Comment by walkert20** [comment]
@kenjarna Well, we figured since you guys are implementing the of the moves of the AI and UI, we figured you come would come up with them because it wouldn't matter what we come up with if you guys don't have a way for us to perform the action.  We were going to implement the frequency in which actions were to occur, like for instance, we were going to have it perform the basic 'attack' at  a certain percentage of times and would have the AI simply call 'Combat' for the 'attack; option.

**Comment by skiadas** [comment]
I think the choice of what actions can be performed would be a joint responsibility of Unit and Combat (and Game perhaps, for out-of-combat actions?). The AI's focus would be more on logic for choosing an action to perform.
