### ISSUE TITLE
Game Design Idea

### ISSUE THREAD

**Issue by Wilcolvan** [skiadas/BattleFTP#14]
Battle for the Point
Lake Lambert has been taken hostage by the faculty of Hanover College and resides at the point. A PSA has gone out that whoever saves Lake Lambert from Hanover College will get free tuition at Hanover. Faculty will be automatically hostile, but other students may or may not be hostile as the reward will only go to one person. Tenuous alliances between students could be a possibility.

**Comment by Wilcolvan** [comment]
Players start out with different abilities based on their knowledge (major) and their origin (building of residence).

**Comment by amartens181** [comment]
Great collaboration work

**Comment by Wilcolvan** [comment]
As soon as the player goes to the point and unties Lake Lambert, all students and faculty converge on the player's location. A speedy escape will be essential.

**Comment by kenjarna** [comment]
Can students "trade" equipment? Are there going to be potions/elixirs?

**Comment by haques94** [comment]
@kenjarna No nerdy shit. We only deal with AK-47s and assault rifles, like real Americans.

**Comment by Wilcolvan** [comment]
Students can trade trade weapons, armor, and "potions." We were going for a more realistic game type, so potions would take the form of things such as "Giant mug of Espresso" or "Healthy Health Shake Bruh"

**Comment by umphreyc19** [comment]
YO WE DOIN A PARTY OR JUST A ONE PERSON TEAM???

**Comment by haques94** [comment]
Just 1.

**Comment by walkert20** [comment]
How about 3 vs. 3 battles at most.

**Comment by hedrickj19** [comment]
I vote just 1.

**Comment by umphreyc19** [comment]
How about you start at one but can expand to three?

**Comment by haques94** [comment]
We're doing it Matrix style. Neo vs an array of Agent Smiths (to start with). If we have time, we'll have the option of creating your own avengers.

**Comment by GrahamLW** [comment]
How do we do progression? You can just walk for five minutes to the point from any place on campus. The game would be way too short if you can beat the game with only five battles.

**Comment by umphreyc19** [comment]
Are we going to have an actual currency in the game?

**Comment by hedrickj19** [comment]
I vote no currency. The user can gain inventory by defeating inventory through out the game, but that is just my opinion. I feel currency adds another level of complexity that isn't necessary.

**Comment by haques94** [comment]
The immortal mind of Kyle Brobby Carson came up with the idea of barter system. We're doing barter system. As for @GrahamLW We'll have missions that we need to complete to achieve stuff. Those stuff will be used to help free Lake.

**Comment by GrahamLW** [comment]
@haques18 So you need to do x quests to free Lake? How do we balance that?

**Comment by Wilcolvan** [comment]
I agree with @hedrickj19 and @haques94. In the event of anarchy the barter system reigns supreme

**Comment by haques94** [comment]
@GrahamLW What do you mean balance that?

**Comment by GrahamLW** [comment]
@haques94 If the intended order is take quest x,y,z what stops someone from doing them as z,x,y? How do we keep the difficulty consistent?

**Comment by PatrickConboy** [comment]
Collin and I talked about the game last night, and one thing we mentioned was having 2/3 different ending depending on how you go about completing the game. You could have an invisible accumulator that changes depending on the choices made that would determine the ending. Could give them the option to do the quests in any order.

**Comment by PatrickConboy** [comment]
Also, we can start by getting a 1 on 1 battle working, and then expand it to more if we want.

**Comment by Wilcolvan** [comment]
I think that we should focus on getting one good ending up and running before we start thinking about multiple endings. We can always conceptualize endings 1, 2, and 3 but in my opinion we shouldn't go into the game with the expectation of multiple endings. I think it would be a nice touch after we have one ending running though.

**Comment by haques18** [comment]
Start at the entrance of the scenic. Car broke down. Walking along Scenic. I meet a student who explains the situation (Faculty holding the President hostage). Afterwards, a faculty member attacks us. Faculty kills the student. Faculty tries to kill me but I manage to defeat him/her. (Faculty member attack will be a tutorial to learn how to fight in the game) 
	
To save the President, I need to acquire the sword of thousand truths. The sword is rumored to be in the library. 

Checkpoint1: I go to the library. I defeat the circ desk student worker, and reference librarians. I go to the top floor of the library and find a part of the sword of a thousand truths hidden in men's urinal. I also find a puzzle in one of the books. The puzzle leads to CFA, Science Hall and cc. CC is the main next checkpoint. Going to CFA or SH will lead to side quests.

Checkpoint2: I need to go to the cc. I have to defeat the sodexo workers. The Soup Nazi knows where the second piece of the sword is. He needs to be defeated in order to get the keys to the bookstore, where the piece is hidden. His last words are, "We do price matching!" In the bookstore, I find the piece and inside a $98.95 price marked book, I find the next puzzle. The puzzle leads to Science Center, Hendricks and Parker. Parker is the main checkpoint and Science Center and Hendricks lead to side quests.

Checkpoint3: I need to go to the Parker. Here I meet the ghost of Parker. If I can defeat him in a 1-on-1 fight, he will tell us where the last piece is hidden. The last piece is the minute hand of the clock in parker. I get up to the clock tower and collect it.

Checkpoint4: I need to go to the point and fight the main bad guy (Hans Gruber) and save the President. I use the sword of thousand truths to fight Hans who has his Morgul blade. I defeat Hans in the sword fight.

I free the President and get free tuition for a semester only.

**Comment by haques18** [comment]
![20171205_224832](https://user-images.githubusercontent.com/25330201/33644138-11a13084-da11-11e7-9c8e-9f4ad090855d.jpg)
@skiadas The attached picture is our basic structure for the game module. If you could comment on the module and let us know what more are we missing (I'm assuming we're missing a lot, I'm just not sure what), that'd be really helpful.
P.S. I forgot to include in the picture, but I'm expecting the fight function is to be obtained from combat (they should have a function that, based on user input does the fighting and updating hero/enemy health stuff)
