### ISSUE TITLE
Work on README

### ISSUE THREAD

**Issue by skiadas** [skiadas/BattleFTP#2]
Take a look at the [README.md](../blob/master/README.md) file. It briefly describes the project, listing a number of top-level modules that might belong to the project, and what each module's responsibilities would be.

Each student must leave at least one comment on this issue, discussing the README so far. Here are some things you might talk about:

1. Do those top-level modules make sense? Do you imagine some part of an RPG-style game that does not fit under those modules? Are those modules truly distinct?
2. Discuss some details that might go into these modules. What are some more specific elements that these modules would need to handle?
3. Make suggestions about elements of the game.

**Comment by amartens181** [comment]
- Game: The Entire Game
  - State: storing, retrieving game information
  - UI: user interaction, input.
  - AI Logic: Enemy Behavior
  - Environment: Game World
    - Art
    - Combat: HP, Values
    - AI Units: Implement AI logic to units

**Comment by hedrickj19** [comment]
- AI: track enemy health and attributes, determine enemy actions, responses, and logic
- Combat: should produce a list of possible actions which are determined by user attributes, user health, battle location, equipment possessed, enemy type, etc. 
- Game: track location of user and AI units, manage the terrain of the game world

**Comment by walkert20** [comment]
1. The Game itself could keep track of the environment, in cases in which the place of battle alters (i.e snow/sandstorm, rain, etc.) It should also keep track of who is fighting and when they fight, as well as general information about the units fighting such as health and status affects. It would also be nice to have a respond function so that the whole function doesn't just close when/if the player's character dies.  On that note, there probably should be an end goal, for example beating a boss, and maybe a world traversal mechanic.  
2. The units, both AI and UI, should have multiple choices of actions, such as attack, defend, flee/run, and wait.  There should also be multiple types of AI and UI units.  AI should also have levels of difficulty.
3. Combat should be turn-based and encountering enemies shouldn't be too frequent.

**Comment by helmersj20** [comment]
I feel like the unit module should be split into AI units and UI units. As it seems to cover too much information in one module, two modules would be easier to maintain than one covering everything.

**Comment by kenjarna** [comment]
Initially, we should create a standard "template" for the equipment that can be used and allow the user to select their set. For simplicity's sake, we should avoid allowing the user to pick and choose particular items initially. 

Also, we need to have an event module that handles events in the game from combat to random events (positive and negative) that can withhold certain events until later in the game (eg, we don't want "boss" fights to happen right out of the gate).

**Comment by skiadas** [comment]
Great suggestions all, keep them coming!

**Comment by roec20** [comment]
a Main menu with some kind of tutorial is key so people know how to play the game. Battles and a few different paths to lead to the end game fight or loot.

**Comment by Hayesb20** [comment]
If we want the game to be Hanover based then some possible attributes we can give the units could be things like: intellect, stamina, luck, where intellect can assume the roll of the attack stat, stamina represents health, and luck can represent the speed/agility/dodge.

**Comment by GrahamLW** [comment]
Character Abilities are good. Just hitting back and forth with big numbers is kind of boring. Things like healing abilities, status abilities, debuffs, etc would make it much more interesting.

This would be both on Combat and on Unit. Combat would have to keep track of all these abilities and Unit would have to keep track of when abilities are available, at what level, at what cost, and whether a unit has a buff, debuff, or status condition.

**Comment by umphreyc19** [comment]
Unit: 

- Should store stats. i.e: Health, Attack, Defense, Magic Attack/Defense (if we want to get that in-depth), and Speed
- Level up growths
- Classes (i.e.: Warrior, Mage, etc...)

Equipment:
- Make it as addition based as possible

UI:
- Since the game should be moderately simple and probably short, save states seem pointless. We should give the user an X amount of tries (probably 3) before they lose entirely
- If the game is too hard, we can add an option to increase the number of lives one has

State:
- Lots of accumulators. Especially on important tasks and events.
- If we make quests for the game, then we need to be able to tell the system that you have either not started on it, are in progress with the quest, or have completed it.

**Comment by veasy62** [comment]
* rename equipment to inventory
* is Unit supposed to be a character? if so possible rename it to character?
* Unlock different languages after defeating each boss, used to upgrade
- Terriyon and Gage

**Comment by amartens181** [comment]
What are we going to do for a [Game engine](http://hackage.haskell.org/packages/#cat:Game%20Engine)
[Resources for Haskell game programming](https://www.quora.com/How-do-I-use-Haskell-in-game-programming)

**Comment by millerlu19** [comment]
Game: Classroom Free For All
                 Goal - last man standing wins, no teams
Unit: User can attack, defend, and wait.  Cannot flee the classroom
                 AI and UI are submodule units
Equipment: Items in LYNN 120A such as - monitor, keyboard, chair, table, backpack, laptop, notebook, pencil, pen, dry erase marker, dry erase eraser, book, wall clock, water bottle, projector remote, projector, cell phone, car keys, shoes, and fists (basically whatever items can be found in the classroom)
Combat: Everyone starts off with the same health; items can be used to hit people or throw at people; can pick up equipment off ground, tables, etc; equipment can be reused; location is only in the classroom (cannot leave); death will result in spectating the rest of the game until the game is over and there is one survivor left.
                          Damage - depends on item being used; if attack lands on enemy's head it counts as double the damage

**Comment by PatrickConboy** [comment]
@amartens181 I think the professor just wants us to keep this as a text based game. So, we wouldn't have any actual visual representations of the game. In other words, we probably don't need any sort of game engine. We would just have accumulators that track different text values, and print out the current state of the game, or what happens in the game, to the user.

**Comment by PatrickConboy** [comment]
Just a general point of discussion I wanted to make, since we only have a month to develop this game; I think it would best if we started out by just focusing on getting a completely bare bones game running, Then we can continue adding more complexity to the game, after we have that up and running correctly. I'm thinking just have a game with a brief introduction, one fight, and you've won the game. That would cover most of the basics of the games implementation. Then, we can work on adding things like multiple encounters, random events, and gear for our character, or whatever else we can think up.

Just some thoughts I had on the development process and how I have seen things done by actual development studios.

**Comment by mundth19** [comment]
@millerlu19 I like that idea. I feel like that could be a simple enough project yet it incorporates a room we are all in everyday. Plus, the fact that we would keep it confined in a single classroom would make it less complex/more realistic than covering a bunch of Hanover's campus.

**Comment by roec20** [comment]
I think creating story mode based game that is text and you are given choices throughout that alter the story ending is the best option right now. when we get that we can add in equipment that effect options and upgrade decisions .

**Comment by haques18** [comment]
**Game**: **HauntedHanover** spans over the entire Hanover Campus. The end goal is to find the map that leads to the cure and then find the patient Zero and apply the cure to patient Zero. User selects actions based on commands typed from the keyboard.
**Unit**: The user may randomly get attacked by zombies on his/her way to the next destination. In these cases, the user will get to use all the weapons he/she has in her backpack. If that doesn't kill all the zombies, the user dies. The user, therefore, needs to collect weapons (offensive and defensive) and make sure he/she has enough weapons to kill all the zombies in his/her way to the destination.
**Equipment**: The equipments are mostly weapons/first aid kit stuff to kill zombies/regain health. The user has to choose what equipments to carry with him in a particular mission, since there is a limited storage in his/her backpack and can either carry numerous small/less threatening weapons or a few large/more fatal weapons. The user may risk discarding the first aid kit and opt to carry more weapons.
**Combat**: Just use keyboard input to apply a weapon from your backpack. You should have a list of all the zombies attacking you and their health conditions and their weaknesses and also the equipments in your backpack and applying an equipment within a time limit is considered a legal combat move.
**Event**: The missions can have 2 different goals.
Goal1: Collecting equipments
Goal2: completing one of the main goals of the game. 
**Main Missions**: Finding map, extracting information form map, finding cure, finding patient zero, applying cure to patient zero
**AI**: Have information about the different types of zombies with each having different weaknesses. Based on the attributes of the zombie attacking, the user can select the weapon to apply against it. As the user finishes each mission, new, resilient types of zombies become activated, that is, the difficulty level of the game increases with every completed mission.
**UI**: Keyboard inputs from the user. The game logic follows from the main game file, with randomness included for zombie attacks to make the game unpredictable.

**Comment by amartens181** [comment]
A text based game eliminates most logic and makes it a Sunday afternoon project 😢
